# Generated by Django 3.0.5 on 2020-04-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poster_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="data_time",),
        migrations.AddField(
            model_name="event",
            name="data_time_begin",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="data_time_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="img_path",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="number_of_tickets",
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="ticket_price",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
