# Generated by Django 3.0.5 on 2020-04-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poster_app", "0004_auto_20200413_1156"),
    ]

    operations = [
        migrations.AddField(
            model_name="typeevent",
            name="plural_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="id_type_exhibition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="poster_app.TypeExhibition",
            ),
        ),
    ]
