# Generated by Django 3.0.5 on 2020-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poster_app", "0006_auto_20200413_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(max_length=2000),
        ),
    ]
