# Generated by Django 3.0.5 on 2020-04-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poster_app", "0007_auto_20200414_0555"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="img_path",),
        migrations.AddField(
            model_name="event",
            name="img",
            field=models.ImageField(
                default="poster_app/static/poster_app/img/defualt.jpg",
                upload_to="Noneevents",
            ),
        ),
    ]
