# Generated by Django 3.0.5 on 2020-04-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poster_app", "0008_auto_20200414_0720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="img",
            field=models.ImageField(
                default="/media/defualt.jpg", upload_to="Noneevents"
            ),
        ),
    ]
