# Generated by Django 3.0.5 on 2020-04-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0009_auto_20200414_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isfree',
            field=models.BooleanField(default=True),
        ),
    ]
