# Generated by Django 3.0.5 on 2020-06-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0010_event_isfree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number_of_tickets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
