# Generated by Django 3.0.5 on 2020-06-06 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0011_auto_20200603_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('ID_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poster_app.UserProfile')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id_setting', models.AutoField(primary_key=True, serialize=False)),
                ('number_booking', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_tickets_booked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('entrance', models.BooleanField(default=True)),
                ('ticket_price', models.CharField(blank=True, max_length=15, null=True)),
                ('isfree', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('ID_event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poster_app.Event')),
                ('id_booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poster_app.Booking')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
