# Generated by Django 3.0.5 on 2020-06-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0012_auto_20200606_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
    ]
