# Generated by Django 3.0.5 on 2020-06-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0013_remove_ticket_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusBooking',
            fields=[
                ('id_status_booking', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'status_booking',
            },
        ),
    ]
