# Generated by Django 3.0.5 on 2020-06-11 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0014_statusbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_status_booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='poster_app.StatusBooking'),
            preserve_default=False,
        ),
    ]
