# Generated by Django 3.0.5 on 2020-06-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0015_booking_id_status_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTicket',
            fields=[
                ('id_type_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'type_ticket',
            },
        ),
    ]
