# Generated by Django 3.0.5 on 2020-06-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0016_typeticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ID_type_ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='poster_app.TypeTicket'),
            preserve_default=False,
        ),
    ]
