# Generated by Django 3.0.5 on 2020-06-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0017_event_id_type_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number_of_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='number_of_tickets_booked',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='entrance',
        ),
    ]
